language: ruby
cache: bundler
script: "bundle exec rake test"
matrix:
  fast_finish: true
  include:
  - rvm: 2.4.1
    env: PUPPET_GEM_VERSION="~> 5.0.0"
  - rvm: 2.4.1
    env: PUPPET_GEM_VERSION="~> 5.1.0"
  - rvm: 2.4.1
    env: PUPPET_GEM_VERSION="~> 5.2.0"
  - rvm: 2.4.3
    env: PUPPET_GEM_VERSION="~> 5.3.0"
  - rvm: 2.4.3
    env: PUPPET_GEM_VERSION="~> 5.4.0"
  - rvm: 2.4.3
    env: PUPPET_GEM_VERSION="~> 5.5.0"
  - rvm: 2.4.3
    env: PUPPET_GEM_VERSION="~> 5"
notifications:
  email: false
